POST  http://localhost:3000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzRmZGQ0M2E4OWVkMDk4NGU2YWExMiIsInVzZXJuYW1lIjoiYWx4IiwiaWF0IjoxNjE4MzY2MDkzfQ.o0uFfPZ5yIcK3AMPF7Lt5VO8FFIseHhYxmKlQDuOOrY

{
    "content": "ahora si funciona con el token",
    "important": true
}
